In [3]:
import numpy as np
import pandas as pd
from copy import deepcopy
k=3
import random as rd
import matplotlib.pyplot as plt

In [7]:
x=pd.read_csv("/home/iignis/Desktop/1NT19IS147_Laisha/kmeans.csv")
print(x)

    X1   X2
0  5.9  3.2
1  4.6  2.9
2  6.2  2.8
3  4.7  3.2
4  5.5  4.2
5  5.0  3.0
6  4.9  3.1
7  6.7  3.1
8  5.1  3.8
9  6.0  3.0


In [10]:
x=x[["X1","X2"]]

In [11]:
x1=x['X1'].values
x2=x['X2'].values

In [12]:
x1

array([5.9, 4.6, 6.2, 4.7, 5.5, 5. , 4.9, 6.7, 5.1, 6. ])

In [13]:
x2

array([3.2, 2.9, 2.8, 3.2, 4.2, 3. , 3.1, 3.1, 3.8, 3. ])

In [15]:
x=np.array(list(zip(x1,x2)))
print(x)

[[5.9 3.2]
 [4.6 2.9]
 [6.2 2.8]
 [4.7 3.2]
 [5.5 4.2]
 [5.  3. ]
 [4.9 3.1]
 [6.7 3.1]
 [5.1 3.8]
 [6.  3. ]]


In [16]:
C_x=[6.2,6.6,6.5]
C_y=[3.2,3.7,3.0]

In [20]:
Centroid=np.array(list(zip(C_x,C_y)))
print("Intial Centroids")
print(Centroid.shape)

Intial Centroids
(3, 2)


In [21]:
Centroid

array([[6.2, 3.2],
       [6.6, 3.7],
       [6.5, 3. ]])

In [22]:
type(Centroid)

numpy.ndarray

In [23]:
Centroid_old=np.zeros(Centroid.shape)
print(Centroid_old)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [24]:
clusters=np.zeros(len(x))
print(clusters)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [29]:
def euclidean(a,b, ax=1):
    return np.linalg.norm(a-b, axis=ax)

In [30]:
error=euclidean(Centroid,Centroid_old,None)
print(error)

12.53714481052205


In [ ]:
while error!=0:
    iterr=itree+1
    for i in range(len(x)):
        distances=euclidean(x[i],Centroid)
        cluster=np.argmin(distances)
        clusters[i]=cluster
    Centroid_old=deepcopy(Centroid)
    print("Old_Centroid")
    print(Centroid_old)
    
    for p in range(k):
        point=[x[j] for j in range (len(x)) if clusters[j] == p]
        Centroid[p]=np.mean(points, axis=0)
    print("New centroids after", iterr, "")